/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinDesignPattern
// import package kotlinDesignPattern.Iterator.*
import kotlinDesignPattern.Iterator.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    println("Iterator")
    kotlinDesignPattern.Iterator.App().main()
}
