/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinDesignPattern


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    kotlinDesignPattern.Iterator.App().main()
    kotlinDesignPattern.Adapter.App().main()
}
